"""add article

Revision ID: 78ab4467718c
Revises:
Create Date: 2020-03-02 17:48:09.918487

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '78ab4467718c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('article_title', sa.Unicode(), nullable=False),
    sa.Column('article_url', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
